### ISSUE TITLE
Archipack 2.0.8 doesn't work with Blender 2.8.74 (2019-06-07 build)

### ISSUE THREAD

**Issue by muratagawa** [s-leger/archipack#111]
Archipack version: 2.0.8

Blender version: 2.8.74 (Date: 2019-06-07 18:51 / Hash: 4fb441517251)

Os version: Windows 10 Home

Description of the issue: Recent version of Archipack crushes Blender when I added just a wall. 

In detail:

1. Open a new file
2. Click "3D Viewport > Create tab > Add Objects > Wall"
3. Select wall from popup
4. Crush

Archipack 2.0.7 has been working with the same version of Blender.

**Comment by muratagawa** [comment]
Sometimes Archipack outputs error messages instead of crush. However when I click the created wall, Blender crushes.

Here is the error:

```
Traceback (most recent call last):
  File "C:\Users\murat\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\archipack_20\archipack_preset.py", line 423, in modal
    op('INVOKE_DEFAULT', **args)
  File "C:\Users\murat\Downloads\blender-2.80.0-git.81b68f7279cd-windows64\2.80\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\murat\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\archipack_20\archipack_object.py", line 418, in invoke
    return self.execute(context)
  File "C:\Users\murat\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\archipack_20\archipack_wall2.py", line 5664, in execute
    self.add_to_reference(context, o)
  File "C:\Users\murat\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\archipack_20\archipack_object.py", line 428, in add_to_reference
    with ensure_select_and_restore(context, ref, [o]):
  File "C:\Users\murat\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\archipack_20\archipack_abstraction.py", line 151, in __init__
    self.ensure_select(obj)
  File "C:\Users\murat\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\archipack_20\archipack_abstraction.py", line 103, in ensure_select
    if o.hide_instance:
AttributeError: 'Object' object has no attribute 'hide_instance'

location: C:\Users\murat\Downloads\blender-2.80.0-git.81b68f7279cd-windows64\2.80\scripts\modules\bpy\ops.py:199


location: <unknown location>:-1
```

I also tried the most recent beta version (2.80 Beta Windows 64 bit June 09, 00:04:40 - 81b68f7279cd), but the result is same.

**Comment by s-leger** [comment]
Hi,
Pushed a hot fix for this issue.
Please re-download and let me know if you still encounter the same issue.

**Comment by muratagawa** [comment]
It seems to be fixed. Thank you for your quick response.
