### ISSUE TITLE
Section Tool issue

### ISSUE THREAD

**Issue by yebyte** [s-leger/archipack#113]
Archipack version:2.08

Blender version:
version: 2.80 (sub 74), branch: blender2.7, commit date: 2019-06-10 23:38, hash: a0608340ae14

Os version:Windows 1809 Ubuntu 18.04 LTS

Description of the issue: 
API Changed
location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\archipack_20\archipack_section.py", line 811, in execute
    dst = d.update_section(context)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\archipack_20\archipack_section.py", line 489, in update_section
    s = self.generate_section(context, sel, pM, clip_x, clip_y)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\archipack_20\archipack_section.py", line 136, in generate_section
    objs = [self.as_mesh(context, o) for o in sel]
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\archipack_20\archipack_section.py", line 136, in <listcomp>
    objs = [self.as_mesh(context, o) for o in sel]
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\archipack_20\archipack_section.py", line 61, in as_mesh
    depsgraph=context.depsgraph,
AttributeError: 'Context' object has no attribute 'depsgraph'

**Comment by s-leger** [comment]
Hi,
Thank you for reporting.
Looks like recent Api changes break this tool, will provide a fix in next release.
