### ISSUE TITLE
Actual blender version and v2.0.9 fails

### ISSUE THREAD

**Issue by nic0711** [s-leger/archipack#114]
Archipack version: 2.0.9

Blender version: Version 2.80 (2.80 2019-06-14)

Os version: MAC OSX Mojave 10.14.5 (18F132)

Description of the issue:
Hi, I have a file that I created with an older version of Blender 2.8 (blender-2.80.0-git20190411.a3b88c917299-x86_64) and ArchiPack v. 2.0.7.
If I open this file with the current versions (see above), many of the features in ArchiPack are not usable.
e.g. I can't create a layout (error message see below)

`Read prefs: /Users/USER/Library/Application Support/Blender/2.80/config/userpref.blend
found bundled python: /Applications/blender.app/Contents/Resources/2.80/python
Archipack PRO 2.0.9 : ready
Read blend: /Users/USER/haus2.blend
Dependency cycle detected:
  MAStair_glass/Shading Component/MATERIAL_UPDATE() depends on
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() via 'Material's NTree'
  MAStair_glass/Shading Component/MATERIAL_UPDATE() via 'Material -> Node'
Dependency cycle detected:
  MAStair_metal/Shading Component/MATERIAL_UPDATE() depends on
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() via 'Material's NTree'
  MAStair_metal/Shading Component/MATERIAL_UPDATE() via 'Material -> Node'
Detected 2 dependency cycles
Traceback (most recent call last):
  File "/Users/USER/Library/Application Support/Blender/2.80/scripts/addons/archipack_20/archipack_object.py", line 418, in invoke
    return self.execute(context)
  File "/Users/USER/Library/Application Support/Blender/2.80/scripts/addons/archipack_20/archipack_section.py", line 730, in execute
    o = self.create(context)
  File "/Users/USER/Library/Application Support/Blender/2.80/scripts/addons/archipack_20/archipack_section.py", line 714, in create
    self.select_object(context, o, True)
  File "/Users/USER/Library/Application Support/Blender/2.80/scripts/addons/archipack_20/archipack_abstraction.py", line 439, in select_object
    o.select_set(state=True, view_layer=context.view_layer)
RuntimeError: Error: Object 'Section.004' not in View Layer 'RenderLayer'!

location: <unknown location>:-1

location: <unknown location>:-1
Dependency cycle detected:
  MAStair_glass/Shading Component/MATERIAL_UPDATE() depends on
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() via 'Material's NTree'
  MAStair_glass/Shading Component/MATERIAL_UPDATE() via 'Material -> Node'
Dependency cycle detected:
  MAStair_metal/Shading Component/MATERIAL_UPDATE() depends on
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() via 'Material's NTree'
  MAStair_metal/Shading Component/MATERIAL_UPDATE() via 'Material -> Node'
Detected 2 dependency cycles
`

When I create a new file, I can create layouts, but I can't create sections.

`Read blend: /Users/USER/test_archpack_2-0-9.blend
Traceback (most recent call last):
  File "/Users/USER/Library/Application Support/Blender/2.80/scripts/addons/archipack_20/archipack_section.py", line 811, in execute
    dst = d.update_section(context)
  File "/Users/USER/Library/Application Support/Blender/2.80/scripts/addons/archipack_20/archipack_section.py", line 489, in update_section
    s = self.generate_section(context, sel, pM, clip_x, clip_y)
  File "/Users/USER/Library/Application Support/Blender/2.80/scripts/addons/archipack_20/archipack_section.py", line 136, in generate_section
    objs = [self.as_mesh(context, o) for o in sel]
  File "/Users/USER/Library/Application Support/Blender/2.80/scripts/addons/archipack_20/archipack_section.py", line 136, in <listcomp>
    objs = [self.as_mesh(context, o) for o in sel]
  File "/Users/USER/Library/Application Support/Blender/2.80/scripts/addons/archipack_20/archipack_section.py", line 61, in as_mesh
    depsgraph=context.depsgraph,
AttributeError: 'Context' object has no attribute 'depsgraph'

location: <unknown location>:-1

location: <unknown location>:-1
`

Both files can be made available via DM if necessary.
@s-leger ... and, aside from that, thanks for the fantastic tool - it gets more stunning with every version!

Cheers, Wolf

**Comment by s-leger** [comment]
Hi Wolf, 

Would be usefull to share the older file so i can investigate and try to fix this issue - perhaps dropbox and pm through either blender-archipack.org contact or blenderartists.
Section error still not fixed in 2.0.9 but will be in 2.0.10

Thank for your kinds words !

**Comment by nic0711** [comment]
Hi Stephen!

Thank’s for your quick reply.
Done.

Regards,
Wolf

Am 15.06.2019 um 13:56 schrieb s-leger <notifications@github.com<mailto:notifications@github.com>>:


Hi Wolf,

Would be usefull to share the older file so i can investigate and try to fix this issue - perhaps dropbox and pm through either blender-archipack.org<http://blender-archipack.org> contact or blenderartists.
Section error still not fixed in 2.0.9 but will be in 2.0.10

Thank for your kinds words !
