### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by hav1v** [s-leger/archipack#130]
Archipack version:1.3.8

Blender version:2.8

Os version:mac

Description of the issue:
Traceback (most recent call last):
  File "/Volumes/Blender/Blender.app/Contents/Resources/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/hav1v/Library/Application Support/Blender/2.80/scripts/addons/archipack-master/__init__.py", line 89, in <module>
    from . import archipack_manipulator
  File "/Users/hav1v/Library/Application Support/Blender/2.80/scripts/addons/archipack-master/archipack_manipulator.py", line 40, in <module>
    from .archipack_gl import (
  File "/Users/hav1v/Library/Application Support/Blender/2.80/scripts/addons/archipack-master/archipack_gl.py", line 1137, in <module>
    class GlCursorFence():
  File "/Users/hav1v/Library/Application Support/Blender/2.80/scripts/addons/archipack-master/archipack_gl.py", line 1141, in GlCursorFence
    def __init__(self, width=1, colour=(1.0, 1.0, 1.0, 0.5), style=bgl.GL_LINE_STIPPLE):
AttributeError: module 'bgl' has no attribute 'GL_LINE_STIPPLE'

**Comment by s-leger** [comment]
Archipack 1.3.8  / 1.40_dev only suppot blender 2.79 
For a blender 2.8 either use official 1.2.8x  or archipack 2.0 available on gumroad.
see https://blender-archipack.org/

**Comment by DSLituiev** [comment]
I purchased a version that claims to support 3.0.0:

`You will find a link to download Archipack version 2.4.0 for blender 2.8x / 2.9x / 3.`

running it with 3.0.0, and still getting this error

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/dlituiev/Library/Application Support/Blender/3.0/scripts/addons/archipack-master/__init__.py", line 89, in <module>
    from . import archipack_manipulator
  File "/Users/dlituiev/Library/Application Support/Blender/3.0/scripts/addons/archipack-master/archipack_manipulator.py", line 40, in <module>
    from .archipack_gl import (
  File "/Users/dlituiev/Library/Application Support/Blender/3.0/scripts/addons/archipack-master/archipack_gl.py", line 1137, in <module>
    class GlCursorFence():
  File "/Users/dlituiev/Library/Application Support/Blender/3.0/scripts/addons/archipack-master/archipack_gl.py", line 1141, in GlCursorFence
    def __init__(self, width=1, colour=(1.0, 1.0, 1.0, 0.5), style=bgl.GL_LINE_STIPPLE):
AttributeError: module 'bgl' has no attribute 'GL_LINE_STIPPLE'
```

**Comment by s-leger** [comment]
Download and setup latest version over, restart blender and then enable the addon.

**Comment by DSLituiev** [comment]
That's what I did. Fresh Blender installation on this machine (Apple Silicon). 
Is there a version later than  2.4.0? That's what I was sent after I purchased it

**Comment by s-leger** [comment]
Use download link in e-mail from blender-archipack.org in order to download archipack 2.4.0
This error is related to 2.0.9 version

**Comment by DSLituiev** [comment]
I followed precisely this instruction:

```
You will find a link to download Archipack version 2.4.0 for blender 2.8x / 2.9x / 3.x

https://blender-archipack.org/archipack/download?t=49efd376049041e084a9df24c916071d&m=mail

Setup instructions
https://blender-archipack.gitlab.io/setup.html


Best regards,
Stephen
```
There it says: "Download Archipack 2.4.0"
That's what I have downloaded. I never used earlier versions on this machine.

**Comment by DSLituiev** [comment]
Got it. Looks like I indeed had an earlier version. Thank you for your help
