### ISSUE TITLE
1.2.8x - Windows creation fails with empty panel

### ISSUE THREAD

**Issue by FredLarson** [s-leger/archipack#133]
Archipack version: 1.2.83

Blender version: 2.8 RC (7/15/2019)

Os version: Mac OS Mojave 10.14.5 (18F132)

Description of the issue: Whenever I change any window parameter such as window height a new panel object is added to the scene and it becomes the becomes the active object.

Reproduce by first creating a window and then change any parameter such as height.

![Before](https://user-images.githubusercontent.com/6607137/61320437-43862380-a7be-11e9-9e18-4a8e548fe65d.png)

Notice the new panel object. All I did was change the height parameter.

![After](https://user-images.githubusercontent.com/6607137/61320484-539e0300-a7be-11e9-8afc-4f8eb1e2ee45.png)

**Comment by s-leger** [comment]
Hi,
Any error message in the console ?
Usually panel should be child of the window, so something goes wrong in the process.

**Comment by FredLarson** [comment]
**### Here is the full console list:**

Freds-iMac:~ fredlarson$ /Applications/Blender.app/Contents/MacOS/Blender 
Read prefs: /Users/fredlarson/Library/Application Support/Blender/2.80/config/userpref.blend
found bundled python: /Applications/Blender.app/Contents/Resources/2.80/python
archipack: ready
Info: Deleted 1 object(s)

Archipack: unable to add material DEFAULT for window
WARN (bpy.rna): /Users/azo/Code/blender/blender_build/blender/source/blender/python/intern/bpy_rna.c:1457 pyrna_enum_to_py: current value '0' matches no enum in 'archipack_material', '', 'material'
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2184, in execute
    o = self.create(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2171, in create
    m.material = self.material
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201
Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2184, in execute
    o = self.create(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2171, in create
    m.material = self.material
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 49, in update
    self.update(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 1414, in update
    self.update_childs(context, o)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 1289, in update_childs
    material=o.archipack_material[0].material
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2184, in execute
    o = self.create(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2171, in create
    m.material = self.material
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201


File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 48, in update
WARN (bpy.rna): /Users/azo/Code/blender/blender_build/blender/source/blender/python/intern/bpy_rna.c:1457 pyrna_enum_to_py: current value '0' matches no enum in 'archipack_material', '', 'material'
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2184, in execute
    o = self.create(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2171, in create
    m.material = self.material
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201
Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2184, in execute
    o = self.create(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2171, in create
    m.material = self.material
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 49, in update
    self.update(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 1414, in update
    self.update_childs(context, o)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 1289, in update_childs
    material=o.archipack_material[0].material
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2184, in execute
    o = self.create(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2171, in create
    m.material = self.material
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201


File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 48, in update

**Comment by s-leger** [comment]
Did you setup the default material library ?
https://github.com/s-leger/archipack/wiki/Materials#material-libraries

**Comment by FredLarson** [comment]
I hadn't set it up, but after I set it up, I still have the same problem. **This is an image of the setup:**

![preferences](https://user-images.githubusercontent.com/6607137/61396280-36c80500-a87c-11e9-9b1d-9d6017a13b97.png)

**Here is the new dump:**

Last login: Wed Jul 17 09:48:17 on ttys000
You have mail.
Freds-iMac:~ fredlarson$ /Applications/Blender.app/Contents/MacOS/Blender 
Read prefs: /Users/fredlarson/Library/Application Support/Blender/2.80/config/userpref.blend
found bundled python: /Applications/Blender.app/Contents/Resources/2.80/python
archipack: ready
Info: Deleted 1 object(s)

Archipack: unable to add material DEFAULT for window
WARN (bpy.rna): /Users/azo/Code/blender/blender_build/blender/source/blender/python/intern/bpy_rna.c:1457 pyrna_enum_to_py: current value '0' matches no enum in 'archipack_material', '', 'material'
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2184, in execute
    o = self.create(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2171, in create
    m.material = self.material
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201
Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2184, in execute
    o = self.create(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2171, in create
    m.material = self.material
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 49, in update
    self.update(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 1414, in update
    self.update_childs(context, o)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 1289, in update_childs
    material=o.archipack_material[0].material
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2184, in execute
    o = self.create(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2171, in create
    m.material = self.material
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201


File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 48, in update
WARN (bpy.rna): /Users/azo/Code/blender/blender_build/blender/source/blender/python/intern/bpy_rna.c:1457 pyrna_enum_to_py: current value '0' matches no enum in 'archipack_material', '', 'material'
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2184, in execute
    o = self.create(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2171, in create
    m.material = self.material
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201
Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2184, in execute
    o = self.create(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2171, in create
    m.material = self.material
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 49, in update
    self.update(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 1414, in update
    self.update_childs(context, o)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 1289, in update_childs
    material=o.archipack_material[0].material
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2184, in execute
    o = self.create(context)
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 2171, in create
    m.material = self.material
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

location: /Applications/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py:201


File "/Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_window.py", line 48, in update
ç

Have you tested your addon on any other Mac? Mojave is the latest version of the MacOS. If I can be of any more help, please let me know. 

Fred

**Comment by s-leger** [comment]
Hi Fred,
Looks like there is something wrong with materials presets not loaded for an unknown reason.
Have a pre-capitain os on my mac and must update to lastest blender as it wont install as it.
I'm travelling till 30 so must wait a bit to be able to debug this issue, but i'd suspect something is wrong with the path handling under mac os, and you're hitting edge case issue with your installation (as nobody else complains about this until now).

**Comment by FredLarson** [comment]
Okay, I hear that MacOS Mojave has tightened security so maybe it's a permissions issue. No problems with other addons so far, even Archimesh. Please keep me informed. I wonder if your pro version has the same issue. When will it be available to test?
Fred

**Comment by s-leger** [comment]
No such issue reported until now on mac os for pro version - available even before 1.2.8x as the latter was a derivative work from 2.x version, benefit from work done on the pro version port. 
Preset loading got huge improvement in the between. 
Presets are stored in user profile, so should not be a write issue - by the way i assume you press once "render presets thumbs".

**Comment by FredLarson** [comment]
I'll buy it on Gumroad and give it a shot. Hopefully it will work!

**Comment by FredLarson** [comment]
Yes, I did generate the thumbnails.

**Comment by s-leger** [comment]
As result the addon should move presets in your user profile. Any special non ascii char / space in user profile name path ?

**Comment by s-leger** [comment]
Are other materials loading successfully ?

**Comment by FredLarson** [comment]
Also, in case I didn't mention it. the wall generator works fine.

**Comment by s-leger** [comment]
You should find "window.txt" in  %user%/.config/blender/2.80/scripts/addons/archipack/presets/archipack_materials/

The original content is 

```
DEFAULT##|##Window_inside
DEFAULT##|##Window_outside
DEFAULT##|##Window_glass
DEFAULT##|##Window_metal
DEFAULT##|##Window_stone
DEFAULT##|##Window_blind
```

**Comment by FredLarson** [comment]
**I found the file "window.txt." On the Mac it is stored here:**

/Users/username//Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/presets/archipack_materials/window.txt

**Here is what the file contains:**

DEFAULT##|##Window_inside
DEFAULT##|##Window_outside
DEFAULT##|##Window_glass
DEFAULT##|##Window_metal
DEFAULT##|##Window_stone
DEFAULT##|##Window_blind

On the Mac addons that are included with the packade are located within the app package. Notice the file path. Addons that are not included with the app package such as Archipack Pro are located in the Mac Application Support folder here:

/Users/username/Library/Application Support/Blender/2.80/scripts/addons/archipack_20

I don't know if this has anything to do with the problem but it may be a permissions problem. As I mentioned, the Mac OS is adding new security all the time.

**Comment by FredLarson** [comment]
In the meantime I purchased the pro version and it seems to work fine! If you wish I will continue to work with you on the problem that I am having with the free version. Like I said, Archimesh works fine on 2.8 on my Mac.

**Comment by s-leger** [comment]
Free version is designed to copy presets into 
/Users/username/Library/Application Support/Blender/2.80/scripts/addons/archipack
when you render thumbs as the floder /Users/username//Applications/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/presets/ is read only by default and was not allowed to add thumbs in the disto.
So possibly an issue with the file copy during the background render process of thumbs.
Anyway, don't mess up your pro setup with free one, will take a closer look at this once back at office.

**Comment by FredLarson** [comment]
Okay. Thanks. The pro version looks like more fun anyway.

**Comment by abecido** [comment]
ok it is working for me.
I removed the the file /home/.config/blender/2.79/scripts/presets/archipack_materials/window.txt

It was like that :

`##|##acajou

##|##acajou

##|##Window_glass

##|##Window_metal

##|##carrelage

##|##Window_blind`

**Comment by s-leger** [comment]
Good catch, will help a lot to narrow down the root of this issue.
Thank for reporting !

**Comment by cyberangel67** [comment]
I am seeing this on Windows 10 with Blender 2.80 as well, I have tried to follow what is going on here, but I am new to Blender, so this is fairly Alien to me.

I expected to add the addon and it would just work, it doesn't.

Adding the default materials and pointing it there as suggest further up, doesn't work either.
