### ISSUE TITLE
dont open bug

### ISSUE THREAD

**Issue by hav1v** [s-leger/archipack#135]
Archipack version:1.2.83

Blender version:2.8

Os version: imac ox 
I installed the new blender and that's what happens when I try to enter the archipack

Description of the issue:

Traceback (most recent call last):
  File "/Volumes/Blender/Blender.app/Contents/Resources/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Volumes/Blender/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/__init__.py", line 69, in <module>
    from . import archipack_manipulator
  File "/Volumes/Blender/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_manipulator.py", line 43, in <module>
    from .archipack_gl import (
  File "/Volumes/Blender/Blender.app/Contents/Resources/2.80/scripts/addons/archipack/archipack_gl.py", line 32, in <module>
    import numpy as np
  File "/Volumes/Blender/Blender.app/Contents/Resources/2.80/python/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/Volumes/Blender/Blender.app/Contents/Resources/2.80/python/lib/python3.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Volumes/Blender/Blender.app/Contents/Resources/2.80/python/lib/python3.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/Volumes/Blender/Blender.app/Contents/Resources/2.80/python/lib/python3.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/Volumes/Blender/Blender.app/Contents/Resources/2.80/python/lib/python3.7/site-packages/numpy/core/__init__.py", line 35, in <module>
    from . import _internal  # for freeze programs
  File "/Volumes/Blender/Blender.app/Contents/Resources/2.80/python/lib/python3.7/site-packages/numpy/core/_internal.py", line 15, in <module>
    import ctypes
  File "/Volumes/Blender/Blender.app/Contents/Resources/2.80/python/lib/python3.7/ctypes/__init__.py", line 543, in <module>
    _reset_cache()
  File "/Volumes/Blender/Blender.app/Contents/Resources/2.80/python/lib/python3.7/ctypes/__init__.py", line 273, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError

bpy.context.area.ui_type = 'INFO'

**Comment by s-leger** [comment]
Hi, take a look at this issue and the way to fix it.
https://github.com/s-leger/archipack/issues/131
