### ISSUE TITLE
'Fit wall to roof' script error

### ISSUE THREAD

**Issue by mark0100** [s-leger/archipack#149]
Archipack version:
1.2.83

Blender version:
2.80.75

Os version:
Ubuntu 18.04

Description of the issue:
If i try to fit a wall to a roof by using the 'Fit roof' button on the Archipack Tab i get the following script error:

-----------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/blender/33/2.80/scripts/addons/archipack/archipack_wall2.py", line 1934, in execute
    r, rd = d.find_roof(context, o, g)
  File "/snap/blender/33/2.80/scripts/addons/archipack/archipack_wall2.py", line 1643, in find_roof
    up)
TypeError: Scene.ray_cast(): error with argument 1, "view_layer" -  Function.view_layer expected a ViewLayer type, not Vector

location: <unknown location>:-1
---------------------------------------------------------------------------------------------------------------------
The wall is then disappeared from the Viewport and is grayed out in the Data Outlier view.
 
I tried moving the wall and roof under the same reference point but this does not solve the problem.

**Comment by s-leger** [comment]
This is a known error, already fixed in source.
Unfortunately the fix was not "cherry picked" for the blender 2.8 release.
Download a daily build.

**Comment by mark0100** [comment]
I installed blender 2.81.15 (beta) but this comes with the same archipack version as 2.80.75 does.

So next i downloaded the latest archipack master branch and tried to install the addon from this zip file (under blender 2.81.15) but i get the following errors if i try to activate it:

-----------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/blender-2.81-cfb6ffd48f77-linux-glibc217-x86_64/2.81/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/mark/.config/blender/2.81/scripts/addons/archipack-master/__init__.py", line 89, in <module>
    from . import archipack_manipulator
  File "/home/mark/.config/blender/2.81/scripts/addons/archipack-master/archipack_manipulator.py", line 40, in <module>
    from .archipack_gl import (
  File "/home/mark/.config/blender/2.81/scripts/addons/archipack-master/archipack_gl.py", line 1137, in <module>
    class GlCursorFence():
  File "/home/mark/.config/blender/2.81/scripts/addons/archipack-master/archipack_gl.py", line 1141, in GlCursorFence
    def __init__(self, width=1, colour=(1.0, 1.0, 1.0, 0.5), style=bgl.GL_LINE_STIPPLE):
AttributeError: module 'bgl' has no attribute 'GL_LINE_STIPPLE'
----------------------------------------------------------------------------------------------------------------------------
 What am i doing wrong here?

**Comment by s-leger** [comment]
Hi Master from this repos work only on blender 2.79 
https://github.com/s-leger/archipack#archipack-for-blender-278--279

The fit roof bug should be fixed on blender side.
https://developer.blender.org/rBA3ee0396ec854f80957dd7061d2980d4923598a3a
as far as i can tell it is fixed in daily build.

**Comment by mark0100** [comment]
Hi,

I patched my local archipack_wall2.py with your fix and now it works. Thanks.

I checked if your fix is in the daily blender build and it is.

Thanks for the help.

Mark
