### ISSUE TITLE
Error when trying to add a window or door etc.

### ISSUE THREAD

**Issue by wifiuk** [s-leger/archipack#178]
Archipack version:
Latest Version Bundled with Blender 2.83
Blender version:
Blender 2.83
Os version:
Windows
Description of the issue:
Having clicked on the create thumbnails button and just let it run, until it looks like nothing is happening I get the following error when trying to add a door or window from the drop down menu.
![image](https://user-images.githubusercontent.com/3785545/84503630-77114c80-acb2-11ea-9558-4eeb8363d67a.png)

**Comment by wifiuk** [comment]
get the same issue in linux

**Comment by s-leger** [comment]
Hi,
This is a known issue, here you'll find a solution.
#137 (comment)

**Comment by wifiuk** [comment]
Indeed I use filmic too. is the fix being backported to the 1.X free version?

**Comment by s-leger** [comment]
If i recall correctly change should be done in 1.x version, perhaps not "cherry picked" as it is not considered as a critical bug.

**Comment by pantallaverde** [comment]
SAME HERE. HOW TO SOLVE IT? CAN'T ADD DOORS BY NO MEANS. CHOSE standard OVER Filmic BUT STILL NOT SOLVED.

bpy.context.space_data.context = 'TOOL'
bpy.context.space_data.context = 'RENDER'
bpy.context.scene.render.engine = 'CYCLES'
bpy.context.scene.cycles.device = 'GPU'
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.shade_smooth()
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.shade_smooth()
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.shade_smooth()
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
Python: Traceback (most recent call last):
  File "C:\Users\amorenva\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\archipack_20\archipack_door.py", line 2196, in modal
    res, tM, wall, width, y, z_offset = self.mouse_hover_wall(context, event)
  File "C:\Users\amorenva\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\archipack_20\archipack_object.py", line 561, in mouse_hover_wall
    res, pt, y, i, o, tM = self.mouse_to_scene_raycast(context, event)
  File "C:\Users\amorenva\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\archipack_20\archipack_object.py", line 539, in mouse_to_scene_raycast
    vec)
  File "C:\Users\amorenva\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\archipack_20\archipack_abstraction.py", line 386, in scene_ray_cast
    direction=vec)
TypeError: Scene.ray_cast(): required parameter "depsgraph" not specified

location: <unknown location>:-1

bpy.context.space_data.context = 'OUTPUT'
bpy.context.space_data.context = 'VIEW_LAYER'
bpy.context.space_data.context = 'SCENE'
bpy.context.space_data.context = 'WORLD'
bpy.context.space_data.context = 'OBJECT'
bpy.context.space_data.context = 'MATERIAL'
bpy.context.space_data.context = 'OBJECT'
bpy.context.space_data.context = 'TOOL'
bpy.context.space_data.context = 'RENDER'
bpy.context.scene.view_settings.view_transform = 'Standard'
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.shade_smooth()
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.shade_smooth()
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.shade_smooth()
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
Python: Traceback (most recent call last):
  File "C:\Users\amorenva\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\archipack_20\archipack_door.py", line 2196, in modal
    res, tM, wall, width, y, z_offset = self.mouse_hover_wall(context, event)
  File "C:\Users\amorenva\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\archipack_20\archipack_object.py", line 561, in mouse_hover_wall
    res, pt, y, i, o, tM = self.mouse_to_scene_raycast(context, event)
  File "C:\Users\amorenva\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\archipack_20\archipack_object.py", line 539, in mouse_to_scene_raycast
    vec)
  File "C:\Users\amorenva\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\archipack_20\archipack_abstraction.py", line 386, in scene_ray_cast
    direction=vec)
TypeError: Scene.ray_cast(): required parameter "depsgraph" not specified

location: <unknown location>:-1

bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.shade_smooth()
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.shade_smooth()
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.shade_smooth()
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
Python: Traceback (most recent call last):
  File "C:\Users\amorenva\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\archipack_20\archipack_door.py", line 2196, in modal
    res, tM, wall, width, y, z_offset = self.mouse_hover_wall(context, event)
  File "C:\Users\amorenva\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\archipack_20\archipack_object.py", line 561, in mouse_hover_wall
    res, pt, y, i, o, tM = self.mouse_to_scene_raycast(context, event)
  File "C:\Users\amorenva\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\archipack_20\archipack_object.py", line 539, in mouse_to_scene_raycast
    vec)
  File "C:\Users\amorenva\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\archipack_20\archipack_abstraction.py", line 386, in scene_ray_cast
    direction=vec)
TypeError: Scene.ray_cast(): required parameter "depsgraph" not specified

location: <unknown location>:-1

**Comment by s-leger** [comment]
Download latest version from blender-archipack.org.
You should find an e-mail with download link.
