### ISSUE TITLE
version 1.38 will not install to blender 2.83.2 (win 10)

### ISSUE THREAD

**Issue by mhdgraphics** [s-leger/archipack#187]
Archipack version: 1.38

Blender version: 2.83.2

Os version: Win 10 (1904)

Description of the issue: Install gives warning message:  Upgrade to 2.8x required. 
selecting activate box give trace back error:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\mike_hughes\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\archipack-master\__init__.py", line 89, in <module>
    from . import archipack_manipulator
  File "C:\Users\mike_hughes\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\archipack-master\archipack_manipulator.py", line 40, in <module>
    from .archipack_gl import (
  File "C:\Users\mike_hughes\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\archipack-master\archipack_gl.py", line 1137, in <module>
    class GlCursorFence():
  File "C:\Users\mike_hughes\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\archipack-master\archipack_gl.py", line 1141, in GlCursorFence
    def __init__(self, width=1, colour=(1.0, 1.0, 1.0, 0.5), style=bgl.GL_LINE_STIPPLE):
AttributeError: module 'bgl' has no attribute 'GL_LINE_STIPPLE'

**Comment by s-leger** [comment]
Version 1.38 / 1.40_dev are compatible with blender 2.79 series only.
Archipack 1.2.8 is shipped with blender 2.8 you only need to enable in preferences->add-ons
Archipack 2.x is available on [gumroad](https://gumroad.com/products/ZRMyP).
