### ISSUE TITLE
Render presets thumbs errors

### ISSUE THREAD

**Issue by HammerDK** [s-leger/archipack#202]
Archipack version: Build in 1.2.83

Blender version: 2.90.0

Os version: Windows 10 Pro (2004)

Description of the issue: Some thumbs are not generated

pack\archipack_floor.py", line 916, in update_manipulators
### RENDER THUMB ############################
Start generating: floor
Prepare camera
Prepare scene
Render
### COMPLETED ############################
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_floor.py", line 917, in update_manipulators
    self.update(context, manipulable_refresh=True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_floor.py", line 1498, in update
    g.floor(context, o, self)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_floor.py", line 343, in floor
    material=-1)
TypeError: bevel: keyword "vertex_only" is invalid for this operator
File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_floor.py", line 916, in update_manipulators
### RENDER THUMB ############################
Start generating: floor
Prepare camera
Prepare scene
Render
### COMPLETED ############################
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_floor.py", line 917, in update_manipulators
    self.update(context, manipulable_refresh=True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_floor.py", line 1498, in update
    g.floor(context, o, self)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_floor.py", line 343, in floor
    material=-1)
TypeError: bevel: keyword "vertex_only" is invalid for this operator
File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_floor.py", line 916, in update_manipulators
### RENDER THUMB ############################
Start generating: floor
Prepare camera
Prepare scene
Render
### COMPLETED ############################
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3458, in update_manipulators
    self.update(context, manipulable_refresh=True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3719, in update
    update_childs=True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 4647, in update
    g.couverture(context, o, self)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 1872, in couverture
    material=-1)
TypeError: bevel: keyword "vertex_only" is invalid for this operator
File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3457, in update_manipulators
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3458, in update_manipulators
    self.update(context, manipulable_refresh=True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 4647, in update
    g.couverture(context, o, self)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 1872, in couverture
    material=-1)
TypeError: bevel: keyword "vertex_only" is invalid for this operator
File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3457, in update_manipulators
### RENDER THUMB ############################
Start generating: roof
Prepare camera
Prepare scene
Render
### COMPLETED ############################
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3458, in update_manipulators
    self.update(context, manipulable_refresh=True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3719, in update
    update_childs=True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 4647, in update
    g.couverture(context, o, self)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 1872, in couverture
    material=-1)
TypeError: bevel: keyword "vertex_only" is invalid for this operator
File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3457, in update_manipulators
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3458, in update_manipulators
    self.update(context, manipulable_refresh=True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 4647, in update
    g.couverture(context, o, self)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 1872, in couverture
    material=-1)
TypeError: bevel: keyword "vertex_only" is invalid for this operator
File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3457, in update_manipulators
### RENDER THUMB ############################
Start generating: roof
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: roof
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: roof
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: roof
Prepare camera
Prepare scene
Render
### COMPLETED ############################
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3458, in update_manipulators
    self.update(context, manipulable_refresh=True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3719, in update
    update_childs=True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 4647, in update
    g.couverture(context, o, self)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 1872, in couverture
    material=-1)
TypeError: bevel: keyword "vertex_only" is invalid for this operator
File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3457, in update_manipulators
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3458, in update_manipulators
    self.update(context, manipulable_refresh=True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 4647, in update
    g.couverture(context, o, self)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 1872, in couverture
    material=-1)
TypeError: bevel: keyword "vertex_only" is invalid for this operator
File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3457, in update_manipulators
### RENDER THUMB ############################
Start generating: roof
Prepare camera
Prepare scene
Render
### COMPLETED ############################
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3458, in update_manipulators
    self.update(context, manipulable_refresh=True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3719, in update
    update_childs=True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 4647, in update
    g.couverture(context, o, self)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 1872, in couverture
    material=-1)
TypeError: bevel: keyword "vertex_only" is invalid for this operator
File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3457, in update_manipulators
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3458, in update_manipulators
    self.update(context, manipulable_refresh=True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 4647, in update
    g.couverture(context, o, self)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 1872, in couverture
    material=-1)
TypeError: bevel: keyword "vertex_only" is invalid for this operator
File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_roof.py", line 3457, in update_manipulators
### RENDER THUMB ############################
Start generating: roof
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: roof
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: roof
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: stair
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: stair
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: stair
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: stair
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: window
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: window
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: window
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: window
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: window
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: window
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: window
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: window
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: window
Prepare camera
Prepare scene
Render
### RENDER THUMB ############################
Start generating: window
Prepare camera
Prepare scene
Render

**Comment by s-leger** [comment]
Thank you for reporting !

Sadly as no one reported in beta phase, will fix for 2.91 release.

**Comment by HammerDK** [comment]
Hi,

thank you for your answer.

I have another problem. Dont know if it is retated to the other problem or if I am doing something wrong.

When I add a new door and use the boolean fuction, the door i added  earlier moves to the same wall as the new door.

**Comment by s-leger** [comment]
Pushed fix in master see [commit log](https://developer.blender.org/rBA8e1b4dd71b37)
Will be backported to 2.90.1 too.
