### ISSUE TITLE
error on render presets thumbs

### ISSUE THREAD

**Issue by toddarchinal** [s-leger/archipack#217]
Archipack version: 1.2.84

Blender version: 2.91

Os version: win 10 home

Description of the issue:
when trying to render presets thumbs it works for a while till i get this error multiple times then locks...

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\archipack\archipack_wall2.py", line 1979, in sp_draw
    if self.state == 'CREATE':
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy_types.py", line 717, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type ARCHIPACK_OT_wall2_draw has been removed

**Comment by s-leger** [comment]
The error occurs because the draw tool for walls is active before running the render thumbs.
Hit either right button or esc to exit.
