### ISSUE TITLE
Error in Archipack while using through command line on ubuntu

### ISSUE THREAD

**Issue by madhura-landge** [s-leger/archipack#233]
Archipack version: 2.1.0

Blender version: 2.91.2
Os version:

Description of the issue:
Blender 2.91.2
Read prefs: /home/brainoidtech/.config/blender/2.91/config/userpref.blend
/usr/share/blender/2.91/scripts/addons/archipack/archipack_py_deps_installer.py:33: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  PYPATH = bpy.app.binary_path_python
Archipack PRO 2.1.0 : ready
Error: Python: Traceback (most recent call last):
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 3031, in execute
    d.manipulable_invoke(context, o)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 3320, in manipulable_invoke
    self.manipulable_setup(context, o)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_floor.py", line 1262, in manipulable_setup
    self.manipulable_setup_parts(context, o)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_curveman.py", line 757, in manipulable_setup_parts
    self.manip_stack.append(part.manipulators[0].setup(context, o, part))
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 2965, in setup
    m = manipulators_class_lookup[self.type_key](
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 2320, in __init__
    DualAngleManipulator.__init__(self, context, o, datablock, manipulator,
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 2149, in __init__
    Manipulator.__init__(self, context, o, datablock, manipulator, snap_callback, start_callback, end_callback)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 338, in __init__
    self.keymap = Keymaps(context)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_keymaps.py", line 51, in __init__
    self.mouse_select = context.window_manager.keyconfigs[0].preferences.select_mouse
AttributeError: 'NoneType' object has no attribute 'select_mouse'

location: /usr/share/blender/2.91/scripts/modules/bpy/ops.py:130

Python: Traceback (most recent call last):
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 3031, in execute
    d.manipulable_invoke(context, o)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 3320, in manipulable_invoke
    self.manipulable_setup(context, o)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_floor.py", line 1262, in manipulable_setup
    self.manipulable_setup_parts(context, o)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_curveman.py", line 757, in manipulable_setup_parts
    self.manip_stack.append(part.manipulators[0].setup(context, o, part))
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 2965, in setup
    m = manipulators_class_lookup[self.type_key](
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 2320, in __init__
    DualAngleManipulator.__init__(self, context, o, datablock, manipulator,
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 2149, in __init__
    Manipulator.__init__(self, context, o, datablock, manipulator, snap_callback, start_callback, end_callback)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 338, in __init__
    self.keymap = Keymaps(context)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_keymaps.py", line 51, in __init__
    self.mouse_select = context.window_manager.keyconfigs[0].preferences.select_mouse
AttributeError: 'NoneType' object has no attribute 'select_mouse'

location: /usr/share/blender/2.91/scripts/modules/bpy/ops.py:130
Error: Python: Traceback (most recent call last):
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 3031, in execute
    d.manipulable_invoke(context, o)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 3320, in manipulable_invoke
    self.manipulable_setup(context, o)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_floor.py", line 1262, in manipulable_setup
    self.manipulable_setup_parts(context, o)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_curveman.py", line 757, in manipulable_setup_parts
    self.manip_stack.append(part.manipulators[0].setup(context, o, part))
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 2965, in setup
    m = manipulators_class_lookup[self.type_key](
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 2320, in __init__
    DualAngleManipulator.__init__(self, conTraceback (most recent call last):
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 3558, in depsgraph_select_post
    auto_manipulate(ctx)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 3510, in auto_manipulate
    bpy.ops.archipack.manipulate(ctx)
  File "/usr/share/blender/2.91/scripts/modules/bpy/ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 3031, in execute
    d.manipulable_invoke(context, o)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 3320, in manipulable_invoke
    self.manipulable_setup(context, o)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_floor.py", line 1262, in manipulable_setup
    self.manipulable_setup_parts(context, o)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_curveman.py", line 757, in manipulable_setup_parts
    self.manip_stack.append(part.manipulators[0].setup(context, o, part))
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 2965, in setup
    m = manipulators_class_lookup[self.type_key](
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 2320, in __init__
    DualAngleManipulator.__init__(self, context, o, datablock, manipulator,
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 2149, in __init__
    Manipulator.__init__(self, context, o, datablock, manipulator, snap_callback, start_callback, end_callback)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_manipulator.py", line 338, in __init__
    self.keymap = Keymaps(context)
  File "/usr/share/blender/2.91/scripts/addons/archipack/archipack_keymaps.py", line 51, in __init__
    self.mouse_select = context.window_manager.keyconfigs[0].preferences.select_mouse
AttributeError: 'NoneType' object has no attribute 'select_mouse'

location: /usr/share/blender/2.91/scripts/modules/bpy/ops.py:130

... truncated
Blender quit

**Comment by s-leger** [comment]
You must update to latest archipack version 2.3.3
For support request about archipack pro use support@blender-archipack.org

**Comment by madhura-landge** [comment]
> You must update to latest archipack version 2.3.3
> For support request about archipack pro use [support@blender-archipack.org](mailto:support@blender-archipack.org)

 where will we get 2.3.3?

**Comment by s-leger** [comment]
Request a link using your gumroad account e-mail in 
https://blender-archipack.org/archipack/update
