### ISSUE TITLE
Can't add windows and doors

### ISSUE THREAD

**Issue by rsx83** [s-leger/archipack#240]
Archipack version: 2.3.4

Blender version: 2.92.0

Os version: Win 10

Description of the issue:

When I try to add door or window there is this error (below). It seems that it adds only a handle but in weird place.
![error](https://user-images.githubusercontent.com/1886679/113766959-5b35d600-971e-11eb-86fe-db1e08656c30.jpg)

Python: Traceback (most recent call last):
  File "C:\Users\roman\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\archipack_20\archipack_window.py", line 3905, in modal
    res, tM, wall, width, y, z_offset = self.mouse_hover_wall(context, event)
  File "C:\Users\roman\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\archipack_20\archipack_object.py", line 561, in mouse_hover_wall
    res, pt, y, i, o, tM = self.mouse_to_scene_raycast(context, event)
  File "C:\Users\roman\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\archipack_20\archipack_object.py", line 539, in mouse_to_scene_raycast
    vec)
  File "C:\Users\roman\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\archipack_20\archipack_abstraction.py", line 386, in scene_ray_cast
    direction=vec)
TypeError: Scene.ray_cast(): required parameter "depsgraph" not specified

location: <unknown location>:-1

**Comment by s-leger** [comment]
Take a look at your e-mails, you should find link to latest version.

**Comment by rsx83** [comment]
Silly me :)
