### ISSUE TITLE
 archipack code refuse to run or refuse to complete "(render preset thumbs)

### ISSUE THREAD

**Issue by Demayors** [s-leger/archipack#272]
Archipack version:

Blender version:2.93

Os version: GTX 10880

Description of the issue: 
![IMG20211005074101](https://user-images.githubusercontent.com/91162202/135974575-ea791978-f497-46b3-8448-a8de449af019.jpg)
good morning, pls i tried using the archipack on my blender and when i click on "render preset thumb" and the code start to run it only stops at the window  level then it hangs and stop there and i have been waiting for hours for it to finish but to no avail

**Comment by Demayors** [comment]
pls i need help

**Comment by s-leger** [comment]
Once done, restart blender.

**Comment by xsellier** [comment]
After restart:
```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/usr/share/blender/scripts/addons/archipack/archipack_preset.py", line 475, in invoke
    self.menu = PresetMenu(context, self.preset_subdir)
  File "/usr/share/blender/scripts/addons/archipack/archipack_preset.py", line 222, in __init__
    self.make_menuitem(filepath)
  File "/usr/share/blender/scripts/addons/archipack/archipack_preset.py", line 299, in make_menuitem
    image.colorspace_settings.name = 'Raw'
TypeError: bpy_struct: item.attr = val: enum "Raw" not found in ('Linear', 'sRGB')

location: <unknown location>:-1
```

**Comment by s-leger** [comment]
This is a known issue with non standard color management addon. 
see #137
