### ISSUE TITLE
Blender 3.0 breaks Archipack 2.3.6 addon presets

### ISSUE THREAD

**Issue by geofizzydrink** [s-leger/archipack#281]
Archipack version: 2.3.6

Blender version: 3.0

Os version: Ubuntu 20.04

Description of the issue:

Blender just autoupdated last night from 2.9.3 to 3.0. I am now getting an error everytime I try to create an Archipack object that opens a preset popup window to select the object style.

I've tested this with every archipack object that this is a requirement for (e.g. wall, window, door,roof,etc...) and they all throw the same error message:

Python: Traceback (most recent call last):
    File "/home/matthew/.config/blender/3.0/scripts/addons/archipack_20/archipack_preset.py", line 477, in invoke
        self.menu = PresetMenu(context, self.preset_subdir)
    File "/home/matthew/.config/blender/3.0/scripts/addons/archipack_20/archipack_preset.py", line 299, in __init__
        _icons = icons.menuitems(category, format)
    File "/home/matthew/.config/blender/3.0/scripts/addons/archipack_20/archipack_iconmanager.py", line 369, in menuitems
        self.load_presets(category, format)
    File "/home/matthew/.config/blender/3.0/scripts/addons/archipack_20/archipack_iconmanager.py", line 260, in load_presets
        folders = bpy.utils.script_paths("presets")
    TypeError: script_paths() takes 0 positional arguments but 1 was given

location:  <unkown location>: - 1

Everything was working in Blender 2.9.3 and all I have done was to copy my 2.9.3 configs across to 3.0. 

Also, in the addon config (under Preferences) I have set the "Material Library" to "/home/matthew/.config/blender/3.0/scripts/addons/archipack_20/presets/"
![archipack-2 3 6-error-Blender3 0](https://user-images.githubusercontent.com/5047294/144682365-0a7e191e-2a0f-456d-8fd4-e2be0fda0377.png)

**Comment by s-leger** [comment]
Archipack 2.3.6 is not compatible with blender 3.0
Fortunately there is a beta 2.3.95 (to be released soon) providing new features and blender 3.0 compatibility.
Request your download link using
https://blender-archipack.org/archipack/beta

**Comment by geofizzydrink** [comment]
Great Thanks!
I figured, based on the error message, that there had been a "breaking" change with Blender 3.0 that would require some refactoring.

I'll check out the 2.3.95 beta version and see how I go.

**Comment by MohamedMamdouh98** [comment]
Oh thank god that beta version is working so far, I was so freaking out because I use it archipak on daily basis. thank you Stephen

**Comment by miarchimi** [comment]
I have the same problem with my Apple M1.
Sadly the bata 2.3.95 is also not working in my Mac :-(
<img width="1112" alt="Image1" src="https://user-images.githubusercontent.com/15873119/144864340-75810919-fa3a-43e1-b830-54f300263ce2.png">
<img width="849" alt="Image2" src="https://user-images.githubusercontent.com/15873119/144864377-83400078-93a7-4811-8fc2-ea07f9de7095.png">

**Comment by s-leger** [comment]
Setup, restart blender, then enable the addon.

**Comment by miarchimi** [comment]
OK, thank's restart of blender did help. Now it's running.
