### ISSUE TITLE
Can't install the archipack addon

### ISSUE THREAD

**Issue by konstantinosfragkoulis** [s-leger/archipack#289]
Archipack version: 1.2.84

Blender version: 2.93.3

Os version: Ubuntu 21.10

Description of the issue: I am trying to install the archipack add-on and I get the following error:

Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/usr/share/blender/scripts/addons/archipack/__init__.py", line 69, in <module>
    from . import archipack_manipulator
  File "/usr/share/blender/scripts/addons/archipack/archipack_manipulator.py", line 43, in <module>
    from .archipack_gl import (
  File "/usr/share/blender/scripts/addons/archipack/archipack_gl.py", line 32, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

I installed numpy(`pip install numpy`) and still get the same error

**Comment by s-leger** [comment]
Setup numpy to the right python interpreter may not be an easy task, take a look at blender's python console for the right one.
Would rather download and setup a portable version of blender from official website.

**Comment by konstantinosfragkoulis** [comment]
I installed blender with snap and it works now.
