### ISSUE TITLE
archipack cannot be installed on blender 3.0

### ISSUE THREAD

**Issue by tobiasriss** [s-leger/archipack#291]
Archipack version: 2.4

Blender version: 3.0

Os version:

Description of the issue:
when activating the plugin I get this error message:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\archipack_20\__init__.py", line 128, in <module>
    glob["archipack_{}".format(sub)] = imp.import_module(".archipack_{}".format(sub), __package__)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\archipack_20\archipack_py_deps_installer.py", line 158, in <module>
    Pip.upgrade_pip()
  File "C:\Users\ USER \AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\archipack_20\archipack_py_deps_installer.py", line 109, in upgrade_pip
    return Pip()._cmd("install", "--upgrade", "pip", verbose=False)
  File "C:\Users\ USER \AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\archipack_20\archipack_py_deps_installer.py", line 73, in _cmd
    return self._run(cmd)
  File "C:\Users\ USER \AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\archipack_20\archipack_py_deps_installer.py", line 85, in _run
    for line in self._popen(cmd):
  File "C:\Users\ USER \AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\archipack_20\archipack_py_deps_installer.py", line 77, in _popen
    for stdout_line in iter(popen.stdout.readline, ""):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 56: invalid continuation byte

**Comment by s-leger** [comment]
Hi Tobias,
Please contact support@blender-archipack.org so i can provide a solution for this issue.
