### ISSUE TITLE
I can not install it on Blender 3.1.2

### ISSUE THREAD

**Issue by byroncos** [s-leger/archipack#322]
Archipack version: 2.3.6

Blender version: 3.1.2

Os version: Windows 11

Description of the issue: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\byron\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\archipack_20\__init__.py", line 126, in <module>
    glob["archipack_{}".format(sub)] = imp.import_module(".archipack_{}".format(sub), __package__)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\byron\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\archipack_20\archipack_py_deps_installer.py", line 151, in <module>
    Pip.ensure_user_site_package()
  File "C:\Users\byron\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\archipack_20\archipack_py_deps_installer.py", line 54, in ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

**Comment by s-leger** [comment]
download latest version 2.4.0, setup over, restart blender then enable.

**Comment by byroncos** [comment]
I can't see any link on gumroad for my updated.... I just have the buy it
button

**Comment by byroncos** [comment]
I already found it!!! Thanks

**Comment by manikls** [comment]
> download latest version 2.4.0, setup over, restart blender then enable.

Thank You. It works

**Comment by byroncos** [comment]
Hi there. I hate this. archioack 2.4 is not working on blender 4.0.1
what's the solution?

**Comment by byroncos** [comment]
looks like you haven't worked with any updates in a while...
