### ISSUE TITLE
Error when extruding walls via the 2d to 3d tool

### ISSUE THREAD

**Issue by kevinwright** [s-leger/archipack#324]
Archipack version: 2.4

Blender version: Confirmed on 3.0.1 and 3.2 stable releases

Os version: Windows 11

Description of the issue:

Attempting to extrude walls (via Alt+E) with the 2d to 3d tools yields the following error:

```
TypeError: update_edit_mesh() takes at most 1 positional argument (2 given)
Error: Python: Traceback (most recent call last):
  File "...\addons\archipack_20\archipack_polylines.py", line 4448, in modal
    return vars_dict['select_polygons'].modal(context, event)
  File "...\addons\archipack_20\archipack_polylines.py", line 1353, in modal
    if self.keyboard(context, event):
  File "...\addons\archipack_20\archipack_polylines.py", line 1321, in keyboard
    return self.complete(context)
  File "...\addons\archipack_20\archipack_polylines.py", line 1147, in complete
    Io.merge_walls(context, self.coordsys, res, z)
  File "...\addons\archipack_20\archipack_polylines.py", line 2735, in merge_walls
    Io.assign_matindex_to_wall(context, wall_0)
  File "...\addons\archipack_20\archipack_polylines.py", line 2683, in assign_matindex_to_wall
    Io.assign_matindex_to_selected(me, mat_index, True)
  File "...\addons\archipack_20\archipack_polylines.py", line 2703, in assign_matindex_to_selected
    bmesh.update_edit_mesh(me, True)
TypeError: update_edit_mesh() takes at most 1 positional argument (2 given)
```

**Comment by s-leger** [comment]
Fixed in 2.5
