### ISSUE TITLE
Archipack Pro 20.9 Not working with Blender 3.2

### ISSUE THREAD

**Issue by BrandonHerrold** [s-leger/archipack#325]
Archipack version: 20.9

Blender version: 3.1.1

Os version: Win 10 Build 21H2

Description of the issue:
Purchased 20.9 - Downloaded All, unpacked to all to a folder, Isntalled Archipack_20.9.zip
Restarted Blender, opened Preferences, add-ons, located Archipack Pro tried to toggle it on, got the following issue:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\Aleno\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\archipack_20\__init__.py", line 112, in <module>
    glob["archipack_{}".format(sub)] = imp.import_module(".archipack_{}".format(sub), __package__)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Aleno\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\archipack_20\archipack_preset.py", line 44, in <module>
    preset_paths = bpy.utils.script_paths("presets")
TypeError: script_paths() takes 0 positional arguments but 1 was given

**Comment by s-leger** [comment]
You should find download link for latest version (2.4+) in e-mail from support@blender-archipack.org sent to you at purchase time.
Once downloaded, setup over, restart blender and enable the addon.
