### ISSUE TITLE
Trouble enabling add on in Blender 3.3

### ISSUE THREAD

**Issue by tytrdev** [s-leger/archipack#332]
Archipack version: Archipack pro 2.5.0

Blender version: 3.3.0

Os version: Windows 10

Description of the issue: I get a python error when trying to enable the addon after installing. Here's a paste of the error:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\tyler\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\archipack_20\__init__.py", line 112, in <module>
    glob["archipack_{}".format(sub)] = imp.import_module(".archipack_{}".format(sub), __package__)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\tyler\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\archipack_20\archipack_preset.py", line 44, in <module>
    preset_paths = bpy.utils.script_paths("presets")
TypeError: script_paths() takes 0 positional arguments but 1 was given
```

My guess is that `script_paths` is an internal function/method that changed in some way with the 3.3 release? Not sure what more I can do to dig into this for you. Would really like to get started with archipack without having to downgrade my blender install though!

**Comment by tytrdev** [comment]
Actually looking at the history for the definition of the method in question, I don't believe anything has changed in a long while. https://github.com/blender/blender/commits/bab9de2a52929fe2b45ecddb1eb09da3378e303b/release/scripts/modules/bpy/utils/__init__.py

Maybe this github mirror is way out of date? I'll keep looking into. I do believe this is roughly a four line change that is impacting multiple users, even people who have purchased the PRO version (such as myself). I'd like to get this fixed ASAP since it should be relatively straightforward.

I did install blender 3.0.1 and try 2.5.0 with that, and I get the same error. I'm trying 3.0.0 now, but I'm assuming I'll get the same error again. Either way I'll be trying to figure out how to update the 4 calls to this method to get it working correctly for 3.3.

**Comment by tytrdev** [comment]
Confirmed that I still get the same error in blender 3.0.0

**Comment by tytrdev** [comment]
Weird conclusion here! Not sure how but I think I ended up with a bad version download to begin with. I believe I used the original download link after purchasing. I was able to get a good version by using this page: https://blender-archipack.org/archipack/update

Looks like I'm all good now! Closing this.
