### ISSUE TITLE
Enabling Archipack 2.5.1 on Blender 3.3.0 fails to enable

### ISSUE THREAD

**Issue by scottshane** [s-leger/archipack#344]
Archipack version: 2.5.1 Pro

Blender version: 3.3.0

Os version: MacOS 12.6  M1 

Description of the issue: 
Addon throws following error when clicking enable checkbox.

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.3/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/██████/Library/Application Support/Blender/3.3/scripts/addons/archipack_20/__init__.py", line 128, in <module>
    glob["archipack_{}".format(sub)] = imp.import_module(".archipack_{}".format(sub), __package__)
  File "/Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/██████/Library/Application Support/Blender/3.3/scripts/addons/archipack_20/archipack_preset.py", line 40, in <module>
    from .archipack_iconmanager import icon_man
ImportError: cannot import name 'icon_man' from 'archipack_20.archipack_iconmanager' (/Users/██████/Library/Application Support/Blender/3.3/scripts/addons/archipack_20/archipack_iconmanager.py)
```

![error_achipack](https://user-images.githubusercontent.com/458382/201216503-ecd3184f-eca4-472b-87d9-dd67b677ed9d.gif)

**Comment by s-leger** [comment]
you must reatart blender before enabling

**Comment by scottshane** [comment]
Same Issue after restart. No additional 3rd party plugins installed. 
deleting `Application Support/Blender` and re-installing Blender 3.3 worked.
