### ISSUE TITLE
Can not enable the add-on on macos (shader compile error)

### ISSUE THREAD

**Issue by dkalna** [s-leger/archipack#385]
Archipack version: 2.6.0

Blender version: 3.6.5 LTS

Os version: macOS Sonoma 14.0

Description of the issue: Can not enable the add-on:

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/dalibor/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/__init__.py", line 128, in <module>
    glob["archipack_{}".format(sub)] = imp.import_module(".archipack_{}".format(sub), __package__)
  File "/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/dalibor/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_manipulator.py", line 4302, in <module>
    class Manipulable:
  File "/Users/dalibor/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_manipulator.py", line 4340, in Manipulable
    manipulable_area = GlCursorArea()
  File "/Users/dalibor/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_gl.py", line 1549, in __init__
    self.border = GlPolyline(bordercolour, d=2, n_pts=4)
  File "/Users/dalibor/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_gl.py", line 928, in __init__
    GlBaseLine.__init__(self, d, n_pts=n_pts)
  File "/Users/dalibor/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_gl.py", line 536, in __init__
    Gl.__init__(self, d)
  File "/Users/dalibor/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_gl.py", line 237, in __init__
    g_poly = GPU_Poly()
  File "/Users/dalibor/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_gl.py", line 136, in __init__
    self.shader = gpu.types.GPUShader(line_vertSrc, line_fragSrc)
Exception: Shader Compile Error, see console for more details

**Comment by m-georgieff** [comment]
I have the same problem!

Archipack version: 2.6.0

Blender version: 3.6.5

Os version: macOS Ventura 13.5.2



<img width="1413" alt="Screenshot 2023-10-24 at 23 07 50" src="https://github.com/s-leger/archipack/assets/124313680/f3e442be-ed9d-4686-8ae6-eb5985c29f79">

**Comment by m-georgieff** [comment]
The solution:

In blender's preferences->system, alter the backend from "Metal" to "OpenGl".

**Comment by Drawxcom** [comment]
> The solution:
> 
> In blender's preferences->system, alter the backend from "Metal" to "OpenGl".

I have the same problem, and try to follow your steps, but after, "system" i can't find the "backend" ? and "metal or OpenGl"?  can you please specify ?
![image](https://github.com/s-leger/archipack/assets/148915373/50cee6c2-4102-4205-872b-4c1f783f0cf2)

**Comment by s-leger** [comment]
This is a mac specific issue.

**Comment by dkalna** [comment]
Hi there, thank you, installation worked fine with backend set to "OpenGL". May I switch back after the installation or does your plugin requieres OpenGL to work properly?

**Comment by s-leger** [comment]
Upcoming release will provide support for Metal and blender 4.x, until then you must keep the backend to OpenGl.

**Comment by dkalna** [comment]
> Upcoming release will provide support for Metal and blender 4.x, until then you must keep the backend to OpenGl.

Ok, thank you for your help.

**Comment by m-georgieff** [comment]
> Hi there, thank you, installation worked fine with backend set to "OpenGL". May I switch back after the installation or does your plugin requieres OpenGL to work properly?

What is the difference between Metal and OpenGL?
