### ISSUE TITLE
Install error M1 Mac

### ISSUE THREAD

**Issue by Zimbakin** [s-leger/archipack#386]
Archipack version: 2.6.0

Blender version: 3.6.5

Os version: 14.0

Description of the issue:

Traceback (most recent call last):

  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/username/Library/Application Support/Blender/3.6/scripts/addons/username_20/__init__.py", line 128, in <module>
    glob["archipack_{}".format(sub)] = imp.import_module(".archipack_{}".format(sub), __package__)
  File "/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/username/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_manipulator.py", line 4302, in <module>
    class Manipulable:
  File "/Users/username/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_manipulator.py", line 4340, in Manipulable
    manipulable_area = GlCursorArea()
  File "/Users/username/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_gl.py", line 1549, in __init__
    self.border = GlPolyline(bordercolour, d=2, n_pts=4)
  File "/Users/username/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_gl.py", line 928, in __init__
    GlBaseLine.__init__(self, d, n_pts=n_pts)
  File "/Users/username/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_gl.py", line 536, in __init__
    Gl.__init__(self, d)
  File "/Users/username/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_gl.py", line 237, in __init__
    g_poly = GPU_Poly()
  File "/Users/username/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_gl.py", line 136, in __init__
    self.shader = gpu.types.GPUShader(line_vertSrc, line_fragSrc)
Exception: Shader Compile Error, see console for more details

username

**Comment by zcztig** [comment]
Having the same problem here.

Blender version 3.6.5
Archipack version 2.6.0

Mac M1 Sonoma 14.0

**Comment by s-leger** [comment]
https://github.com/s-leger/archipack/issues/363#issuecomment-1491725456
