### ISSUE TITLE
TypeError: GPUShader.uniform_float() argument 1 must be str, not int

### ISSUE THREAD

**Issue by haukj** [s-leger/archipack#390]
Archipack version: 2.7

Blender version:3.6 - Metal GPU Backend enabled

Os version:Mac OS 14.2

Description of the issue:
Issue with values being passed as strings in the GPU_Poly Class and GPU_Line Class. Resulting in no thumbs are showing in the UI when creating walls, windows, doors etc.

Error message: 
Traceback (most recent call last):
  File "/Users/username/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_preset.py", line 370, in draw_handler
    self.menu.draw(context)
  File "/Users/username/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_preset.py", line 296, in draw
    self.border.draw(context)
  File "/Users/username/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_gl.py", line 612, in draw
    g_line.draw(self.colour, list_verts_co)
  File "/Users/username/Library/Application Support/Blender/3.6/scripts/addons/archipack_20/archipack_gl.py", line 157, in draw
    self.shader.uniform_float(self.unif_color, self.color) #, 4)
TypeError: GPUShader.uniform_float() argument 1 must be str, not int

I fixed the classes and tested it on my Mac, and it works fine (easy fix).

@s-leger Let me know if you want me to share the code with you :)

**Comment by s-leger** [comment]
You should download 2.7.2 version using the link in e-mail for original release, or request a new download link using About tab at bottom of Create panel.
