### ISSUE TITLE
Errors archipack 1.3.8 community edition not compatible with blender 4.0

### ISSUE THREAD

**Issue by wkunz50** [s-leger/archipack#392]
Archipack version: 
1.3.8

Blender version: 
4.01

Os version: 
Windows 11

Description of the issue:  
I installed Archipack without problems. But when I activate it, I get his...
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\wtkun\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\archipack-master\__init__.py", line 89, in <module>
    from . import archipack_manipulator
  File "C:\Users\wtkun\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\archipack-master\archipack_manipulator.py", line 40, in <module>
    from .archipack_gl import (
  File "C:\Users\wtkun\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\archipack-master\archipack_gl.py", line 1137, in <module>
    class GlCursorFence():
  File "C:\Users\wtkun\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\archipack-master\archipack_gl.py", line 1141, in GlCursorFence
    def __init__(self, width=1, colour=(1.0, 1.0, 1.0, 0.5), style=bgl.GL_LINE_STIPPLE):
AttributeError: module 'bgl' has no attribute 'GL_LINE_STIPPLE'

It then remains inactive. I also have Clean Panels installed. Would this cause a problem?
Thank you.

**Comment by jumalakarhu** [comment]
I get the same. I also have Blender 3.6 installed parallell to 4.0 where this error occurs

**Comment by s-leger** [comment]
Archipack "community edition" compatible with blender 3 is available on gumroad's store.
https://blender-archipack.gumroad.com/l/ZUrMf

Archipack pro provide support for blender 4.x
https://blender-archipack.gumroad.com/l/ZRMyP
