### ISSUE TITLE
error when activating add-on macOS

### ISSUE THREAD

**Issue by cekuhnen** [s-leger/archipack#402]
Archipack version:
2.0.9
Blender version:
4.1
Os version:
macos 14.4.1

Description of the issue:

after installing the add-on and trying to activate it this happens:

Traceback (most recent call last):
  File "/Applications/Blender 4.1.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender 4.1.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ez5554/Library/Application Support/Blender/4.1/scripts/addons/archipack_20/__init__.py", line 112, in <module>
    glob["archipack_{}".format(sub)] = imp.import_module(".archipack_{}".format(sub), __package__)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender 4.1.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ez5554/Library/Application Support/Blender/4.1/scripts/addons/archipack_20/archipack_preset.py", line 44, in <module>
    preset_paths = bpy.utils.script_paths("presets")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: script_paths() takes 0 positional arguments but 1 was given

**Comment by s-leger** [comment]
You should find a download link for latest release (2.8.0) in e-mail from support@blender-archipack.org
Once downloaded, setup over, restart blender then enable the addon.
