### ISSUE TITLE
Can't Install Blender 4.1.1

### ISSUE THREAD

**Issue by whurst121280** [s-leger/archipack#405]
Archipack version:  2.8

Blender version: 4.1.1

Os version: Windows 10

Description of the issue:

Can't install

Traceback (most recent call last):
  File "E:\Blender\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Blender\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\archipack_20\__init__.py", line 128, in <module>
    glob["archipack_{}".format(sub)] = imp.import_module(".archipack_{}".format(sub), __package__)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Blender\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\archipack_20\archipack_manipulator.py", line 4360, in <module>
    class Manipulable:
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\archipack_20\archipack_manipulator.py", line 4398, in Manipulable
    manipulable_area = GlCursorArea()
                       ^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\archipack_20\archipack_gl.py", line 1549, in __init__
    self.title_area.draw(context)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\archipack_20\archipack_gl.py", line 928, in __init__
    # bgl.glDisable(bgl.GL_BLEND)
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\archipack_20\archipack_gl.py", line 536, in __init__
    unit = "sq " + unit
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\archipack_20\archipack_gl.py", line 240, in __init__
    )
      
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\archipack_20\archipack_gl.py", line 174, in __init__
    self.color[0:4] = color[0:4]
              ^^^^^^^^^^^^^^^^^^^
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '2D_IMAGE'

**Comment by s-leger** [comment]
For some reason your blender does not report the true version.
Is it a beta / instable one ?
You may try to open the script console and enter
`bpy.app.version` 
in order to confirm, should be (4.1.x)

**Comment by whurst121280** [comment]
Sorry it is Blender 4.1.1 that was a typo. Fixed initial post to reflect proper version.

**Comment by s-leger** [comment]
Go into "Scripting" workspace, and type
`bpy.app.version`
and then press enter in the console (the black window with green text), then report the result.

**Comment by whurst121280** [comment]
That is what it reported.

**Comment by s-leger** [comment]
To me looks like a familiar issue related to setup of release 2.6 or 2.6 beta instead of 2.8.0 
see https://github.com/s-leger/archipack/issues/399
If it still fails for you, please contact by e-mail support@blender-archipack.org
