### ISSUE TITLE
activation impossible archipack pro

### ISSUE THREAD

**Issue by ginger-witch** [s-leger/archipack#406]
Archipack version: 2.0.9 and 2.8.0

Blender version: 4.0

Os version: win 10

Description of the issue:
bonjour je viens juste d'acheter la version pro et pas moyen de l'activer 

(j'avais tester avent la version gratuit tout etait ok sur mon blender v3 (j'ai réinstaller la version free et jai installer sur mon blender 4.0 et cela me donne une erreur au moment de l'activer.)

j'ai trouver pour telecharer une autre version dans le mail  (la version 2.8.0) mais j'ai toujours le meme probleme

***************************************

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\cc_hd\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\archipack_20\__init__.py", line 112, in <module>
    glob["archipack_{}".format(sub)] = imp.import_module(".archipack_{}".format(sub), __package__)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\cc_hd\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\archipack_20\archipack_preset.py", line 44, in <module>
    preset_paths = bpy.utils.script_paths("presets")
TypeError: script_paths() takes 0 positional arguments but 1 was given

V 2.0.9
![archipack-bug](https://github.com/s-leger/archipack/assets/172768243/0e08dad1-5896-4c93-954b-fe83f8acbc17)

V 2.8.0
![image](https://github.com/s-leger/archipack/assets/172768243/7ec040f7-901e-48b2-98f3-58646aba6af1)

**Comment by ginger-witch** [comment]
Problem résolu ^^
Apres un 3 iem désinstallation, un nouveau redémarrage de blender et la reinstallation de la version 2.8.0 tout est rentrée dans l'ordre

et tout fonctionne 
♥
