### ISSUE TITLE
Archipack 1.2.x "community edition" not  compatible with blender 4.x

### ISSUE THREAD

**Issue by IINasK** [s-leger/archipack#409]
Archipack version:
1.2.85
Blender version:
4.1
Os version:

Description of the issue:
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\archipack\archipack_wall2.py", line 1785, in execute
    o = self.create(context)
        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\archipack\archipack_wall2.py", line 1776, in create
    m.auto_smooth_angle = 0.20944
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'auto_smooth_angle'

**Comment by s-leger** [comment]
Archipack commnnity edition is not compatible with blender 4.x
you may either rely on archipack pro or blender 3.x
