### ISSUE TITLE
Archipack 2.4 not working on blender 4.0.1

### ISSUE THREAD

**Issue by byroncos** [s-leger/archipack#410]
Archipack version: 2.4

Blender version: 4.0.1

Os version: windows 11

Description of the issue:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\byroncos\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\archipack_20\__init__.py", line 128, in <module>
    glob["archipack_{}".format(sub)] = imp.import_module(".archipack_{}".format(sub), __package__)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\byroncos\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\archipack_20\archipack_manipulator.py", line 4298, in <module>
    class Manipulable:
  File "C:\Users\byroncos\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\archipack_20\archipack_manipulator.py", line 4336, in Manipulable
    manipulable_area = GlCursorArea()
  File "C:\Users\byroncos\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\archipack_20\archipack_gl.py", line 1541, in __init__
    self.border = GlPolyline(bordercolour, d=2, n_pts=4)
  File "C:\Users\byroncos\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\archipack_20\archipack_gl.py", line 920, in __init__
    GlBaseLine.__init__(self, d, n_pts=n_pts)
  File "C:\Users\byroncos\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\archipack_20\archipack_gl.py", line 535, in __init__
    Gl.__init__(self, d)
  File "C:\Users\byroncos\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\archipack_20\archipack_gl.py", line 239, in __init__
    g_image = GPU_Image()
  File "C:\Users\byroncos\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\archipack_20\archipack_gl.py", line 174, in __init__
    self.shader = gpu.shader.from_builtin('2D_IMAGE')
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '2D_IMAGE'

**Comment by s-leger** [comment]
sent download link for updated release.

**Comment by byroncos** [comment]
Thank you sir

**Comment by byroncos** [comment]
I didn't had chance to dowload materials... looks like the link it's one
time
