### ISSUE TITLE
fail to install on blender 4.1 and 4.0

### ISSUE THREAD

**Issue by DAMitchell70** [s-leger/archipack#412]
Archipack version:2.0.9

Blender version: 4.1 and 4.0

Os version: Windows 10

Description of the issue:
attempt to install it on 4.1 and 4.0 and got the following error code

Traceback (most recent call last):
  File "E:\BlenderFoundation\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\BlenderFoundation\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\sinpe\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\archipack_20\__init__.py", line 112, in <module>
    glob["archipack_{}".format(sub)] = imp.import_module(".archipack_{}".format(sub), __package__)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\BlenderFoundation\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\sinpe\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\archipack_20\archipack_preset.py", line 44, in <module>
    preset_paths = bpy.utils.script_paths("presets")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: script_paths() takes 0 positional arguments but 1 was given

**Comment by ivicnunez** [comment]
I am also unable to install. I get error

**Comment by s-leger** [comment]
see https://github.com/s-leger/archipack/issues/368#issuecomment-1536471248
