### ISSUE TITLE
Can not install Archipack 20.9 in Blender 4.3.0 in Ubuntu 24.10

### ISSUE THREAD

**Issue by etxealaikoion** [s-leger/archipack#418]
Archipack version: 20.9

Blender version: 4.3.0

Os version: Ubuntu 24.10

Description of the issue: I'm getting the following error while installing the add-on

Python: Traceback (most recent call last):
  File "/snap/blender/5562/4.3/scripts/addons_core/bl_pkg/bl_extension_ops.py", line 1458, in execute
    cmd_batch = self.exec_command_iter(is_modal)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/blender/5562/4.3/scripts/addons_core/bl_pkg/bl_extension_ops.py", line 2537, in exec_command_iter
    self.exec_legacy(source_filepath)
  File "/snap/blender/5562/4.3/scripts/addons_core/bl_pkg/bl_extension_ops.py", line 2669, in exec_legacy
    bpy.types.PREFERENCES_OT_addon_install.execute(self, bpy.context)
  File "/snap/blender/5562/4.3/scripts/startup/bl_operators/userpref.py", line 813, in execute
    bpy.ops.preferences.addon_enable(module=mod.__name__)
  File "/snap/blender/5562/4.3/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: script_paths() takes 0 positional arguments but 1 was given

**Comment by s-leger** [comment]
You must downlaod latest release using the link in e-mail from support@blender-archipack.org
Once downloaded, setup over, restart blender then enable the addon.

**Comment by etxealaikoion** [comment]
Thanks, it worked.
